#!/bin/bash 

# Bash script to partition .gitignore amongst varying remotes 

cat .origin_ignore > .gitignore
git push origin main

cat .private_ignore > .gitignore
git push private main

cat .origin_ignore > .gitignore



