#!/bin/bash 

# Bash script to partition .gitignore amongst varying remotes 

cat .origin_ignore > .gitignore
git push origin main

git checkout main-private
git pull private main
git merge main
cat .private_ignore > .gitignore
git push private main

git checkout main
cat .origin_ignore > .gitignore

